# Generated by Django 4.2.16 on 2024-09-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopet', '0002_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='adress',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
