# Generated by Django 4.2.16 on 2024-09-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopet', '0003_shelter_about_alter_shelter_adress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('adopted', models.BooleanField(default=False)),
                ('age', models.CharField(max_length=50)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopet.shelter')),
            ],
        ),
    ]
