# Generated by Django 4.2.16 on 2024-10-02 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopet', '0004_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adopet.pet')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopet.tutor')),
            ],
        ),
    ]
